version: '3.8'

services:
  app:
    volumes:
      - .:/var/www/html
      - maintenance_new_storage:/var/www/html/storage/app

  scheduler:
    volumes:
      - .:/var/www/html
      - maintenance_new_storage:/var/www/html/storage/app
